### ISSUE TITLE
Playbook stalls while installing packages

### ISSUE THREAD

**Issue by bhedana** [debops/ansible-slapd#22]
I'm new to ansible and debops 
I've created a very simple playbook that looks like this

```
---
# common
- hosts: all
  become: yes
  gather_facts: no
  roles:
    - debops.bootstrap

# ldap
- hosts: ldap
  become: yes
  roles:
    - debops.slapd
```

when executed the playbook gets to the task on installing ldap packages and stalls
```
TASK: [debops.slapd | Install OpenLDAP packages] ****************************** 
```

checking the process list on the ldap host looks like it's stalled in the preconfigure phase
``` 
5363 pts/0    Ss+    0:00 /bin/sh -c sudo -k && sudo -H -S -p "[sudo via ansible, key=phfikyezteerdkehoqdohudooszwqwmz] password: " -u root /bin/s
 5365 pts/0    S+     0:00 sudo -H -S -p [sudo via ansible, key=phfikyezteerdkehoqdohudooszwqwmz] password:  -u root /bin/sh -c echo BECOME-SUCCESS
 5366 pts/0    S+     0:00 /bin/sh -c echo BECOME-SUCCESS-phfikyezteerdkehoqdohudooszwqwmz; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /
 5367 pts/0    S+     0:00 /usr/bin/python /home/devops/.ansible/tmp/ansible-tmp-1457737293.83-184039930891776/apt
 5371 pts/0    S+     0:00 /usr/bin/apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold install slapd --no-install-rec
 5375 pts/0    Z+     0:00 [dpkg] <defunct>
 5376 pts/0    S+     0:00 /bin/sh -c /usr/sbin/dpkg-preconfigure --apt || true
 5377 pts/0    R+     3:52 /usr/bin/perl -w /usr/sbin/dpkg-preconfigure --apt
 5379 pts/0    Z+     0:00 [dpkg-preconfigu] <defunct>
 5385 pts/0    R+     0:49 /bin/sh /tmp/slapd.config.nTc50X configure 
```

perhaps i'm missing some configuration.. 
or perhaps something else has gone awry..
any assist would be appreciated

**Comment by drybjed** [comment]
What OS is this, Debian, Ubuntu? Which release? Can you try installing `slapd` manually and checking with `debconf-get-selections | grep slapd` from the `debconf-utils` package what questions are asked by `debconf`?

You shouldn't need to use `debops.bootstrap` role all the time, but you might want to add `debops.core` role.

**Comment by bhedana** [comment]
this is Ubuntu 14.04.3

debconf output
```
slapd	slapd/password1	password	
slapd	slapd/internal/generated_adminpw	password	
slapd	slapd/internal/adminpw	password	
slapd	slapd/password2	password	
slapd	slapd/dump_database_destdir	string	/var/backups/slapd-VERSION
slapd	slapd/move_old_database	boolean	true
slapd	slapd/allow_ldap_v2	boolean	false
# Do you want the database to be removed when slapd is purged?
slapd	slapd/purge_database	boolean	false
slapd	slapd/backend	select	BDB
slapd	shared/organization	string	
slapd	slapd/dump_database	select	when needed
slapd	slapd/password_mismatch	note	
slapd	slapd/no_configuration	boolean	false
slapd	slapd/upgrade_slapcat_failure	error	
slapd	slapd/domain	string	
slapd	slapd/invalid_config	boolean	true
```

**Comment by drybjed** [comment]
Hmm, so perhaps a more extensive list of `debconf` answers is needed. I'll look into it when I get some time, can you try installing `slapd` on Debian Jessie and checking of it works there?

**Comment by bhedana** [comment]
results appear to be the same using debian 8.3.0

**Comment by bhedana** [comment]
poking at this again.. back in Ubuntu 14.04.3

looking back at the debconf output it appears that values aren't being set for 
slapd/password1
slapd/password2
slapd/domain
shared/organization

just as an experiment i created entries in the playbook to set values for the two passwords..
i'm puzzled why the domain was not present as that looks like it should default to the ansible_domain 
but i set a var on the ldap host for slapd_domain and the output looks more complete..
```
slapd	slapd/internal/generated_adminpw	password	supersecret
slapd	slapd/password1	password	supersecret
slapd	slapd/password2	password	supersecret
slapd	slapd/internal/adminpw	password	{SSHA}supersecret
slapd	slapd/invalid_config	boolean	true
slapd	slapd/password_mismatch	note	
# Do you want the database to be removed when slapd is purged?
slapd	slapd/purge_database	boolean	true
slapd	slapd/domain	string	testdomain.lan
slapd	shared/organization	string	testdomain.lan
slapd	slapd/move_old_database	boolean	true
slapd	slapd/backend	select	HDB
slapd	slapd/allow_ldap_v2	boolean	false
slapd	slapd/no_configuration	boolean	false
slapd	slapd/dump_database	select	when needed
slapd	slapd/upgrade_slapcat_failure	error	
slapd	slapd/dump_database_destdir	string	/var/backups/slapd-VERSION

```

this at least leads to a different error..
```
failed: [ldap] => (item=slapd,ldap-utils,python-ldap) => {"failed": true, "item": "slapd,ldap-utils,python-ldap"}
stderr:   Moving old database directory to /var/backups:
  - directory unknown... done.
  Creating initial configuration... Loading the initial configuration from the ldif file () failed with
the following error while running slapadd:
    ldif_read_record: include file:///etc/ldap/schema/core.ldif failed
dpkg: error processing package slapd (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 slapd
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by drybjed** [comment]
I just tried to set up `slapd` on freshly installed Debian Jessie, the server installed without issues.

You are using a custom playbook for this, can you try using the default DebOps playbook and running:
```
debops common -l host
debops service/slapd -l host
```
to see if everything works in default environment? There may be something that's needed and is configured by a different role (`debops.apt`? not sure). If everything works, that might be it, but if you get the same error, there must be an issue with the host itself...

**Comment by bhedana** [comment]
so it would appear that my original issue was the lack of the ansible_domain var being set..
switching back to default playbooks and running on fresh jessie hosts the only complaint now is that the ssl-cert group does not exist.. 
```
TASK: [debops.slapd | Add OpenLDAP system user to additional groups] ********** 
failed: [ldap] => {"failed": true}
msg: Group ssl-cert does not exist
```
but that should be easy enough to correct
