### ISSUE TITLE
error when you run the role

### ISSUE THREAD

**Issue by le9i0nx** [debops/ansible-slapd#24]
```
ansible 2.0.1.0
```

```
16:29 le9i0nx:~/crypt/ansible$ ansible-playbook service/slapd.yml --limit ldap
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/le9i0nx/crypt/ansible/roles/debops.slapd/tasks/main.yml': line 56, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Set slapd log level
  ^ here
```

**Comment by drybjed** [comment]
If you use a custom playbook, you might need to add `ldap_addr` and `ldap_entry` modules from `debops-playbooks` for the LDAP support to work. They are located in the `debops-playbooks` instead of individual roles to make maintenance simplier, since that way all roles can use the same version of modules.

**Comment by le9i0nx** [comment]
yes I have them pre-updated

**Comment by drybjed** [comment]
Hmm. Not sure what's happening then... I'll try `debops.slapd` role on a host and get back to you.

**Comment by drybjed** [comment]
OK, I've enabled `debops.slapd` on a host and ran it, Ansible errored on a task later in the role, but the relevant modules worked. Check the Ansible `library` configuration variable in `ansible.cfg`, see if it points to the directory with the modules.

**Comment by le9i0nx** [comment]
it's okay now.
I did the patch documentation.

#23

**Comment by drybjed** [comment]
Wait, what? What was the issue and what did you do to fix it?

**Comment by le9i0nx** [comment]
I added a line ansible.cfg
```
library        = /etc/ansible/library
```
