### ISSUE TITLE
Travis-CI fails when running slapd rolespec

### ISSUE THREAD

**Issue by ganto** [debops/ansible-slapd#27]
Since a few months all Travis-CI runs for `debops.slapd` [fail](https://travis-ci.org/debops/ansible-slapd/branches) to run with the following error(s):

    TASK [ansible-slapd : Configure LDAP connection security] **********************
    fatal: [testing-gce-66a661ac-efba-4706-9b50-0b1126b45cc4.c.eco-emissary-99515.internal]:   
    FAILED! => {"changed": false, "exc": "Traceback (most recent call last):\n
    File \"/tmp/ansible_qh3icR/ansible_module_ldap_attr.py\", line 170, in main\n
    LdapAttr(module).main()\n  
    File \"/tmp/ansible_qh3icR/ansible_module_ldap_attr.py\", line 230, in main\n
    self.connection.modify_s(self.dn, modlist)\n
    File \"/usr/lib/python2.7/dist-packages/ldap/ldapobject.py\", line 322, in modify_s\n
    return self.result(msgid,all=1,timeout=self.timeout)\n
    File \"/usr/lib/python2.7/dist-packages/ldap/ldapobject.py\", line 422, in result\n
    res_type,res_data,res_msgid = self.result2(msgid,all,timeout)\n
    File \"/usr/lib/python2.7/dist-packages/ldap/ldapobject.py\", line 426, in result2\n
    res_type, res_data, res_msgid, srv_ctrls = self.result3(msgid,all,timeout)\n
    File \"/usr/lib/python2.7/dist-packages/ldap/ldapobject.py\", line 432, in result3\n
    ldap_result = self._ldap_call(self._l.result3,msgid,all,timeout)\n
    File \"/usr/lib/python2.7/dist-packages/ldap/ldapobject.py\", line 96, in _ldap_call\n
    result = func(*args,**kwargs)\nOTHER: {'info': '<olcSecurity> unknown factor',
    'desc': 'Other (e.g., implementation specific) error'}\n",
    "failed": true, "msg": "{'info': '<olcSecurity> unknown factor',
    'desc': 'Other (e.g., implementation specific) error'}"}

I found that this won't happen with Ansible 2.0.2.0 (Jessie Backports) therefore we should adjust the test suite to successfully test the code changes again.

**Comment by drybjed** [comment]
I disagree. To me the issue seems `slapd`-specific:
```
'<olcSecurity> unknown factor',
'desc': 'Other (e.g., implementation specific) error'}\n",
"failed": true, "msg": "{'info': '<olcSecurity> unknown factor',
'desc': 'Other (e.g., implementation specific) error'}
```
This usually means that the Python LDAP library tried to make changes which were rejected by the `slapd` server. It seems like some LDAP entries are wrong or mismatched. `olcSecurity` is sometimes tricky to implement when you enable higher security level everywhere without ensuring that the internal access either uses the proper security level or still has access to the LDAP server.

**Comment by drybjed** [comment]
Besides, if we stick to a specific Ansible version, then what happens when Ansible moves on? Do we stay on that specific version forever? I would rather fix the issue with the Python LDAP library instead. :-)

**Comment by ganto** [comment]
I agree that this is a work-around at best. However, the issue is pending since more than 3 months and several pull-requests are pending because of it.

How about adding the work-around for the time being and then open an issue for the correct fix? I guess most of the people are using DebOps with Debian Jessie (and Ansible from Backports) where the role is still working fine. If they want to send pull requests, they shouldn't be blocked by that.

**Comment by drybjed** [comment]
Wery well, I'll switch to Ansible 2.0 for this role Travis tests.
