### ISSUE TITLE
<olcSecurity> unknown factor

### ISSUE THREAD

**Issue by bhedana** [debops/ansible-slapd#30]
I've set up a basic project implementing this role.
[project repo](https://github.com/BurnerCodeSchool/debops)
[full output](https://gist.github.com/bhedana/3a504dbfd1be78b094ac2339a8f09ea9)
I am setting no specific configuration vars for ldap.. accepting all defaults

when run:
TASK [debops.slapd : Configure LDAP connection security] ***********************
reports:
"msg": "{'info': '<olcSecurity> unknown factor', 'desc': 'Other (e.g., implementation specific) error'}"}

I'm using the [example playbook](https://docs.debops.org/en/latest/ansible/roles/ansible-slapd/docs/getting-started.html#example-playbook) from docs

perhaps i'm missing required config or doing something else wrong

hosts: 
control: linux mint 18
hosts: debian jessie

**Comment by drybjed** [comment]
It looks to be an issue with order of the various LDAP features enabled on the server. I'll look into it shortly to find the problem.

**Comment by drybjed** [comment]
@bhedana OK, I've checked the role on a test host, and it looks like you encountered the [Ansible 2.1 raw module parameters issue](https://github.com/ansible/ansible/issues/16057). Try running the role on Ansible 2.0 (I tested this on `stable-2.0` branch, runs fine).

It's a known issue with `ldap_attr` and `ldap_entry` custom modules used by this role, we are looking into a fix for Ansible 2.1.

**Comment by drybjed** [comment]
@bhedana I've merge the [ldap module fix](https://github.com/debops/debops-playbooks/pull/297) provided by @anzil in the `debops-playbooks` repository. Can you check if that fixes the issues you encountered on Ansible 2.1?

**Comment by bhedana** [comment]
I apologize for taking so long to circle back onto this 
but yes 
using the latest versions of playbooks the issue appears to have been resolved
